server:  
  port: 20001
  context-path: /up
  session-timeout: 30
  tomcat: 
    uri-encoding: UTF-8
message: hello world

spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/appdb
    username: app
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

